name: Build Godot Project

on:
  push: {}
  pull_request: {}

jobs:
  Godot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux, HTML5, windows, mac]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Build
        id: mossism_proto-build
        uses: manleydev/build-godot-action@v1.4.1
        with:
          name: Mossism-proto
          preset: ${{ matrix.platform }}
          package: "true"
          debugMode: "false"
          build: ./builds
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
